#!/usr/bin/env python3
"""Generate the synthetic assets used by the demo.

Why a script instead of a committed photo:

* Reproducible. The asset is regenerated byte-for-byte, so it is never a
  mystery binary in the repository.
* Licensed. No third-party photograph, so no attribution question.
* Honest. The image is obviously synthetic, which matters because the classifier
  output for it is *not* a meaningful claim about the model. It exists to make
  the UI demo-able with no camera and no downloaded weights.

Expect low-confidence, arbitrary labels from this image. That is a property of
running ImageNet classification on a drawing, not a bug -- and the UI shows the
scores, so the wrongness is visible rather than hidden.

Usage:
    python scripts/make_sample_assets.py
"""

from __future__ import annotations

import sys
import wave
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from snapdragoon import config  # noqa: E402

ASSETS = config.PROJECT_ROOT / "assets"


def _make_jpg(path: Path) -> None:
    from PIL import Image, ImageDraw

    w, h = 800, 600
    img = Image.new("RGB", (w, h), (222, 226, 232))
    d = ImageDraw.Draw(img)

    # Wall: soft vertical gradient.
    for y in range(0, int(h * 0.72), 2):
        t = y / (h * 0.72)
        d.rectangle(
            [0, y, w, y + 2],
            fill=(int(236 - 22 * t), int(238 - 20 * t), int(242 - 16 * t)),
        )

    desk_y = int(h * 0.72)
    d.rectangle([0, desk_y, w, h], fill=(142, 98, 62))
    d.rectangle([0, desk_y, w, desk_y + 6], fill=(112, 76, 46))
    for x in range(0, w, 26):  # faint grain so it is not a flat slab
        d.line([(x, desk_y + 6), (x, h)], fill=(136, 94, 60), width=1)

    # Mug, left of the laptop.
    mx, my = 168, desk_y - 92
    d.ellipse([mx, my, mx + 84, my + 92], fill=(238, 238, 234))
    d.rectangle([mx, my + 8, mx + 84, my + 88], fill=(238, 238, 234))
    d.ellipse([mx + 60, my + 22, mx + 112, my + 62], outline=(226, 226, 222), width=9)
    d.ellipse([mx + 10, my + 4, mx + 74, my + 20], fill=(74, 52, 38))

    # Laptop: base, then screen, then a lit panel.
    bx, by = 300, desk_y
    d.polygon([(bx, by), (bx + 400, by), (bx + 372, by + 40), (bx + 28, by + 40)],
              fill=(196, 199, 204))
    d.polygon([(bx + 60, by + 8), (bx + 340, by + 8), (bx + 322, by + 32),
               (bx + 78, by + 32)], fill=(168, 172, 178))

    sx, sy, sw, sh = 300, by - 300, 400, 300
    d.rectangle([sx, sy, sx + sw, sy + sh], fill=(52, 55, 60))
    d.rectangle([sx + 12, sy + 12, sx + sw - 12, sy + sh - 12], fill=(38, 62, 96))
    # A few brighter bars so the "screen" is not a single flat rectangle.
    for i, (oy, oh) in enumerate([(40, 22), (76, 14), (104, 30), (148, 18),
                                  (180, 24), (218, 12)]):
        d.rectangle([sx + 34, sy + oy, sx + 34 + 180 - i * 14, sy + oy + oh],
                    fill=(126, 176, 226))

    img.save(path, "JPEG", quality=88)
    print(f"  [ok]   {path.relative_to(config.PROJECT_ROOT)}  {img.size[0]}x{img.size[1]}")


def _make_wav(path: Path) -> None:
    """16 kHz mono: 3 s tone, 3 s silence, 3 s tone, 3 s silence.

    The silence gaps are the point. They exercise the ``skip`` branch of the
    caption stream, so the demo shows both a caption and a skipped window
    without anyone having to sit in a quiet room to record it.
    """
    sr = config.SAMPLE_RATE
    tone = (0.3 * np.sin(2 * np.pi * 220 * np.linspace(0, 3, 3 * sr, endpoint=False))
            ).astype(np.float32)
    silence = np.zeros(3 * sr, dtype=np.float32)

    path.parent.mkdir(parents=True, exist_ok=True)
    with wave.open(str(path), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(sr)
        for seg in (tone, silence, tone, silence):
            w.writeframes((seg * 32767).astype(np.int16).tobytes())
    print(f"  [ok]   {path.relative_to(config.PROJECT_ROOT)}  "
          f"{path.stat().st_size // 1024} KB  16 kHz mono")


def main() -> int:
    print(f"\nGenerating synthetic assets in {ASSETS}\n")
    ASSETS.mkdir(parents=True, exist_ok=True)
    try:
        _make_jpg(ASSETS / "sample.jpg")
    except ImportError:
        print("  [MISS] Pillow is required for the sample image: pip install pillow")
    _make_wav(ASSETS / "sample.wav")
    print("\n  Reminder: the classifier's output for sample.jpg is not a real-world\n"
          "  claim. Use a photograph for that.\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
